version: "3"

services:

    nginx:
        image: nginx
        # ports: # 8080番ポートで外部からhttp接続可能
        #     - "8080:80"
        expose:
            - "80"

    https-portal:
        image: steveltn/https-portal:1
        ports:
            - "80:80"
            - "443:443"
        links:
            - nginx
        restart: always
        environment:
            STAGE: local
            DOMAINS: "localweb.test -> http://nginx:80"
            # STAGE: "production" # ドメイン名を設定すればLet's Encryptを使用可能
            # DOMAINS: "production.domain -> http://nginx:80"
            # FORCE_RENEW: "true"
        volumes: 
            - ./https-portal-data:/var/lib/https-portal
